name: Push Code
#e
on:
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master
    types:
      - closed 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
     
      - name: install clever cloud
        run: |
          sudo apt install gpg
          sudo apt install curl
          curl -fsSL https://clever-tools.clever-cloud.com/gpg/cc-nexus-deb.public.gpg.key | sudo gpg --dearmor -o /usr/share/keyrings/cc-nexus-deb.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/cc-nexus-deb.gpg] https://nexus.clever-cloud.com/repository/deb stable main" | sudo tee -a /etc/apt/sources.list
          sudo apt-get update
          sudo apt-get install clever-tools

      - name: Ajouter la clé SSH pour Clever Cloud
        env:
          SSH_PRIVATE_KEY: ${{ secrets.CLEVER_SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan push-n3-par-clevercloud-customers.services.clever-cloud.com >> ~/.ssh/known_hosts

      - name: Installer GIT
        run: sudo apt update | sudo apt install git -y
      
      - name: Configurer Git pour GitHub Actions
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"

      - name: Supprimer un éventuel fichier lock de Git
        run: rm -f .git/index.lock

      - name: Deploy github
        run: |
             git remote add clever git+ssh://git@push-n3-par-clevercloud-customers.services.clever-cloud.com/${{ secrets.APP_ID_DEV }}.git 
             git add .
             git commit -m "Mise à jour automatique via CI/CD" || echo "Aucune modification à commit"
             git push clever master --force
      

      - name: SET VENV
        run: |
             clever login --token ${{ secrets.CLEVER_TOKEN }} --secret ${{ secrets.CLEVER_SECRET }}
             clever link ${{ secrets.APP_ID_DEV }} --alias FRONT_PROD
             nohup clever restart --alias FRONT_PROD > /dev/null 2>&1 &
    